###
POST http://192.168.0.120:8080/api/auth/register

{
    "email": "das@123",
    "password": "Rg547571856g#",
    "phone": "1231231dad231233",
    "is_adm": true
}

###
POST http://192.168.0.120:8080/api/auth/login

{

    "email": "gustavo.dsa12@aluno.ifsc.edu.br",
    "password": "Rg547571856g#"
}

###
GET http://localhost:8080/api/auth/me
Authorization: Bearer v2.local.oJBOR1l2mBC9gLDXnI2h5Ollvwmk0xqNenyj6gYd7e7PqGFX1q4VH4q_PLet5iXvxjZQos7Bx4x4M--b5-piXZraWy07KP9a7kwE6ynJu_pwGAVb2-_YEq5qhs3DrzACW490Q_BIq8q-0ugrXbCT1RcuOVPYXTJ4IPGmzycwGNzuhjkQ5TeaDRCuS4zQCkA3D5QSwDO2yGf4pGkR6kk3QfbU75-Htt60y4PJ6dGM2YGb-r3-seETQSprNGNaUrhAOEBJCBF0wBUvwvz8mX-OmHo2-vxE6wBhFAmg9eNJbTfvq7J4_ZlDf03LBRPSPxcDeLfxqVJ8dg.bnVsbA