###
POST http://192.168.0.120:8080/api/auth/register

{
    "email": "das@123",
    "password": "Rg547571856g#",
    "phone": "1231231dad231233",
    "is_adm": true
}

###
POST http://192.168.0.120:8080/api/auth/login

{

    "email": "gustavo.dsa12@aluno.ifsc.edu.br",
    "password": "Rg547571856g#"
}

###
POST http://192.168.0.120:8080/api/auth/me
Authorization: Bearer v2.local.AKLjem9ReAWXkdl8ufFCKT-439npnY68Dv5YueAbL1veA0ZjPeykPV6daU-Belmd0LfFWQ-nrYO-X7suQarskTC2Tx9HolfPg8UXnAj4b7_U8f-C4ynMw5m9E6QQAGpFhMBxhYg8UmC6j1TzEeUURbEAL_qNFPgI1U0Dc3-sERk0vUB3gh36OqLxAiB2uzQMCZRvx9PqCuaP25cHvnMos0gbFARxeyfOWxObQct8UVJddwQtaSr3qre3kVHOscFEJQr7pk55W0fbJX7rQrGiZplJ8Di0iMkKOeLOCAVZGbiMbDHwW6nT1WA0Ky0uPGhSzPUUl8asNA.bnVsbA