###
GET http://localhost:8080/api/product

###
GET http://localhost:8080/api/product?limit=5&page=1

###
@get_id = 1
GET http://localhost:8080/api/product/{{get_id}}

###
POST http://192.168.0.120:8080/api/product
Authorization: Bearer v2.local.VzfJ_WpYN5HYordVZI270Ak-esr1ePhuXFfJKZoaz7BkSHFvxep1Oh1p6V3RDhNn9bDig5-qJQBk4_Q07gu9p47BP8v7GshPaCZ8AvrD67R0jEX_GbsjxX39vqAOl7d4Qm4BpBlRGEG3xx-OO9wKcugERFxz9OcZU5v771hYQW6enTNFl8ZD95CB1tXGKyUteFfP4A8uNRMYvyP5rnwMGFW-JyNo6vOmLJHTZYhLhfGlYl9A_reXn6JJj1NwtGAE8drciy9kM1ZJRuOYmVOitid9p2bDb5XxeuLIXZdEE_fgsarzBOdX32_2wuvlJbT2YFj4jfvILw.bnVsbA
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Cachaça Ouro
--WebAppBoundary
Content-Disposition: form-data; name="description"

Cachaça armazenada em tonel de jequitibá
--WebAppBoundary
Content-Disposition: form-data; name="price"

19.99
--WebAppBoundary
Content-Disposition: form-data; name="stock"

30
--WebAppBoundary
Content-Disposition: form-data; name="photos"; filename="garrafa.jpg"
Content-Type: image/jpeg

< ./assets/cachaca.jpg
--WebAppBoundary--

###
@delete_id = 1
DELETE http://localhost:8080/api/product/{{delete_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg3NDg3MDksInVzZXJfaWQiOjF9.cU6pCBoRbh2DVBUXvdai0YGsZEpGwraDj_wEBfph1DQ