services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cachacadb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    image: gsdagustavo/cachacaria-api
    depends_on:
      - mysql
    environment:
      DB_DRIVER: mysql
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: cachacadb
      SERVER_PORT: 8080
      SERVER_ADDRESS: 192.168.0.120
      JWT_SECRET: secret
      BASE_URL: http://192.168.0.120
    ports:
      - "8080:8080"
    volumes:
      - products_images:/app/images
      - ./logs:/app/logs

volumes:
  mysql_data:
  products_images:
  logs: