###
GET http://localhost:8080/products

###
GET http://localhost:8080/products?limit=5&page=1

###
@get_id = 1
GET http://localhost:8080/products/{{get_id}}

###
POST http://localhost:8080/products/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTkyMzg1ODcsInVzZXJfaWQiOjF9.khRtIkeW4oSgjKgI2Uj6lh-zvvOhVuIqeQ-7EgGI97Y
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Cachaça Ouro
--WebAppBoundary
Content-Disposition: form-data; name="description"

Cachaça armazenada em tonel de jequitibá
--WebAppBoundary
Content-Disposition: form-data; name="price"

19.99
--WebAppBoundary
Content-Disposition: form-data; name="stock"

30
--WebAppBoundary
Content-Disposition: form-data; name="photos"; filename="garrafa.jpg"
Content-Type: image/jpeg

< ./assets/cachaca.jpg
--WebAppBoundary--

###
@delete_id = 1
DELETE http://localhost:8080/products/delete/{{delete_id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTg3NDg3MDksInVzZXJfaWQiOjF9.cU6pCBoRbh2DVBUXvdai0YGsZEpGwraDj_wEBfph1DQ